apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: next-prodcatui
  labels:
    oda.tmforum.org/componentName: next-prodcatui
spec:
  type: next-prodcatui
  selector:
    matchLabels:
     oda.tmforum.org/componentName: next-prodcatui
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment  
  version: "0.0.1"
  description: "Vodafone simple reference implementation of ODA Product Catalog." 
  maintainers:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com   
  coreFunction:
    exposedAPIs: []
    dependantAPIs: 
    - name: productcatalog:2.0.0
      specification: https://open-api.tmforum.org/TMF620-ProductCatalog-v4.0.0.swagger.json
      ref: next-prodcatui.env.PRODUCTCATALOG_API_URL
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    securitySchemes:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-prodcatui
  labels:
    oda.tmforum.org/componentName: next-prodcatui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-prodcatui
  template:
    metadata:
      labels:
        app: next-prodcatui
    spec:
      containers:
      - name: next-prodcatui
        image: lesterthomas/next-productcatalog-ui:0.7
        ports:
        - name: next-prodcatui
          containerPort: 4200
        env:
        - name: PRODUCTCATALOG_API_URL
          value: 'http://gke-dev.ddns.net/'            
        - name: DOCUMENTMANAGEMENT_API_URL
          value: 'http://gke-dev.ddns.net/'            
        - name: SHOW_ATTACHMENTS_LINK
          value: 'true'
        - name: ATTACHMENTS_URL
          value: '/attachments'            
---
apiVersion: v1
kind: Service
metadata:
  name: next-prodcatui
  labels:
    app: next-prodcatui
    oda.tmforum.org/componentName: next-prodcatui
spec:
  ports:
  - port: 4200
    targetPort: next-prodcatui
    name: next-prodcatui
  type: LoadBalancer
  selector:
    app: next-prodcatui
---