apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: next-productcatalog
  labels:
    oda.tmforum.org/componentName: next-productcatalog
spec:
  type: ocs
  selector:
    matchLabels:
     oda.tmforum.org/componentName: next-productcatalog
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment  
  version: "0.0.1"
  description: "Vodafone-Next implementation of TM Forum Product Catalog Component." 
  maintainers:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com     
  coreFunction:
    exposedAPIs: 
    - name: productCatalog
      specification: https://raw.githubusercontent.com/tmforum-rand/oda-component-definitions/wso2APIOperator/components/vodafone-next-productcatalog.swagger.json?token=ABYIJPTOQC65GK6JMKLGSC263AK4M
      implementation: next-pc
      port: 8191
      path: /catalogManagement
      developerUI: /catalogManagement/swagger-ui.html
    dependantAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: []
  security:
    securitySchemes: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-pc
  labels:
    oda.tmforum.org/componentName: next-productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-pc
  template:
    metadata:
      labels:
        app: next-pc
    spec:
      serviceAccountName: odacomponent-account
      initContainers:
      - name: pod-dependency
        image: ylonkar/pod-dependency-init-container:1.0.2
        env:
        - name: POD_LABELS
          value: app=next-mongo
        - name: MAX_RETRY
          value: "10"
        - name: RETRY_TIME_OUT
          value: "5000"
      containers:
      - name: next-pc
        image: lesterthomas/next-productcatalog:1.0.3
        env:
        - name: MONGO_DB_URL
          value: "next-mongo:27017"
        ports:
        - name: next-pc
          containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: next-pc
  labels:
    app: next-pc
    oda.tmforum.org/componentName: next-productcatalog
spec:
  ports:
  - port: 8191
    targetPort: next-pc
    name: next-pc
  type: NodePort
  selector:
    app: next-pc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-mongo
  labels:
    oda.tmforum.org/componentName: next-productcatalog
    app: next-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-mongo
  template:
    metadata:
      labels:
        app: next-mongo
    spec:
      containers:
      - name: next-mongo
        image: lesterthomas/next-mongo-productcatalog:0.0.5
        ports:
        - name: next-mongo
          containerPort: 27017
        volumeMounts:
        - name: next-mongo-pv-storage
          mountPath: "/data/db"
      volumes:
      - name: next-mongo-pv-storage
        persistentVolumeClaim:
          claimName: next-mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: next-mongo
  labels:
    oda.tmforum.org/componentName: next-productcatalog
    app: next-mongo
spec:
  ports:
  - port: 27017
    targetPort: next-mongo
    name: next-mongo
  type: NodePort
  selector:
    app: next-mongo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: next-mongo-pv-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi    
