apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: ProductCatalogCanagement
    oda.tmforum.org/funtionalBlockName: Core Commerce Management
    name: Tag_Release_Name - ProductCatalogCanagement
spec:
  componentKinds:
  - group: core
    kind: Service
  - group: core
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  coreFunction:
    exposedAPIs:
    - name: ProductInventory
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF637-ProductInventory-v4.0.0.swagger.json
      apitype: openapi
      implementation: {{.Release.Name}}-ProductInventory
      path: {{.Release.Name}}-{{.Values.component.type}}tmf-apiproductInventoryv4
      developerUI: {{.Release.Name}}-{{.Values.component.type}}tmf-apiproductInventoryv4docs
      port: 8080
    dependantAPIs:
    - name: ProductCatalogManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      apitype: openapi
  management: 
    exposedAPIs:
    - name: metrics
      apitype: prometheus
  security:
    controllerRole: {{ .Values.security.controllerRole }}
    exposedAPIs: 
    - name: partyrole
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: {{.Release.Name}}-partyroleapi
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      port: 8080      
  maintainers:
  - email: kamal.maghsoudlou@ericsson.com
    name: Kamal Maghsoudlou
  owners:
  - email: kamal.maghsoudlou@ericsson.com
    name: Kamal Maghsoudlou
  type: TMFC-001-productcatalogmanagement
  version: 0.0.1